### ISSUE TITLE
Feature Request: Allow pandoc-zotxt to create permanent citation file

### ISSUE THREAD

**Issue by CxRes** [egh/zotxt#9]
This request is to allow pandoc-zotxt to create permanent citation file (perhaps in the same folder as the original file), avoiding the need run pandoc-zotxt every time that pandoc is used to recreate a document but citations have not changed.

**Comment by odkr** [comment]
This has already been implemented. The new Lua filter, pandoc-zotxt.lua, does this. If I’m not mistaken, it ships with newer versions of zotxt. Just set the `zotero-bibliography` metadata field to a filename (must end with ".json", because it must be, you know, a JSON file). That file will be created in the directory of the first input file passed to pandoc. But have a look at the [documentation of pandoc-zotxt.lua for details](https://github.com/odkr/pandoc-zotxt.lua/blob/master/man/pandoc-zotxt.lua.md).

**Comment by egh** [comment]
Closing because the python `pandoc-zotxt` is obsolete and deprecated.
